package skills

import (
	"strings"
	"testing"
	"time"
)

func liveContext() ProjectContext {
	return ProjectContext{
		CLIVersion:        "0.1.0",
		GeneratedAt:       time.Date(2026, 9, 16, 17, 12, 0, 0, time.UTC),
		Profile:           "dev",
		BaseURL:           "http://localhost:3900",
		APIPath:           "/api",
		DiscoveryRevision: "2026-09-16T17:00:00Z",
		PayloadVersion:    "3.86.0",
		AuthCollection:    "users",
		AuthMode:          "api-key",
		Collections: []CollectionInfo{
			{Slug: "pages", Singular: "Page", IDType: "number", TotalDocs: 11,
				Ops:      []string{"create", "read", "update", "delete"},
				Features: []string{"drafts", "versions"}, KeyFields: []string{"title", "slug", "_status"}},
			{Slug: "crm-contacts", Singular: "CrmContact", IDType: "number", TotalDocs: 104,
				Ops:      []string{"create", "read", "update", "delete"},
				Features: []string{"trash", "folders"}, KeyFields: []string{"name", "email", "status"}},
			{Slug: "media", Singular: "Media", IDType: "number", TotalDocs: 4,
				Ops:      []string{"create", "read", "update", "delete"},
				Features: []string{"upload", "folders"}, KeyFields: []string{"alt", "filename"}},
			{Slug: "payload-migrations", Internal: true, IDType: "number",
				Ops: []string{"read"}, KeyFields: []string{"name"}},
		},
		Globals: []GlobalInfo{
			{Slug: "header", Features: []string{"versions"}},
			{Slug: "footer"},
		},
	}
}

func TestRenderProject(t *testing.T) {
	got := string(RenderProject(liveContext()))

	tests := []struct {
		name string
		want string
	}{
		{"header comment", `<!-- generated by pay 0.1.0 on 2026-09-16T17:12:00Z from profile "dev"`},
		{"header second line", "base_url=http://localhost:3900 discovery_revision=2026-09-16T17:00:00Z -->"},
		{"snapshot disclaimer", "This is a SNAPSHOT and may be stale."},
		{"explain is live", "`pay explain` is always live"},
		{"refresh command", "pay skills update --project-only"},
		{"collection count", "## Collections (4)"},
		{"a real slug", "| `pages` |"},
		{"internal marked", "*(internal)*"},
		{"globals", "## Globals (2)"},
		{"a real global", "| `header` |"},
		{"auth collection", "The auth collection is **`users`**"},
		{"exact header form", "Authorization: users API-Key <your key>"},
		{"examples", "pay describe pages --required-only"},
		{"drafts example", "pay find pages --published-only --limit 5"},
		{"globals example", "pay globals get header --depth 1"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if !strings.Contains(got, tc.want) {
				t.Errorf("PROJECT.md is missing %q:\n%s", tc.want, got)
			}
		})
	}
}

func TestRenderProjectOrdersCollections(t *testing.T) {
	got := string(RenderProject(liveContext()))
	order := []string{"crm-contacts", "pages", "media", "payload-migrations"}
	last := -1
	for _, slug := range order {
		i := strings.Index(got, "| `"+slug+"`")
		if i < 0 {
			t.Fatalf("%s is missing", slug)
		}
		if i < last {
			t.Fatalf("%s is out of order (non-internal first, then most documents)", slug)
		}
		last = i
	}
}

func TestRenderProjectNeverLeaksACredential(t *testing.T) {
	ctx := liveContext()
	ctx.BaseURL = "https://admin:paycli-dev-key-deadbeefdeadbeef@example.com"
	ctx.Profile = "token=paycli-dev-key-deadbeefdeadbeef"
	got := string(RenderProject(ctx))
	for _, bad := range []string{"paycli-dev-key-deadbeefdeadbeef", "admin:"} {
		if strings.Contains(got, bad) {
			t.Fatalf("PROJECT.md leaked %q:\n%s", bad, got)
		}
	}
}

func TestRenderProjectDegradesGracefully(t *testing.T) {
	// Discovery returned nothing useful: the file must still render, still say
	// it is a snapshot, and still tell the reader where to get the truth.
	got := string(RenderProject(ProjectContext{
		GeneratedAt: time.Date(2026, 9, 16, 17, 12, 0, 0, time.UTC),
	}))
	for _, want := range []string{
		"generated by pay dev",
		"This is a SNAPSHOT",
		"## Collections (0)",
		"This project has no globals.",
		"Authorization: <authCollection> API-Key <your key>",
		"pay describe <collection> --required-only",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("degraded PROJECT.md is missing %q:\n%s", want, got)
		}
	}
}

func TestExamplesFallBacks(t *testing.T) {
	tests := []struct {
		name string
		ctx  ProjectContext
		want string
	}{
		{
			name: "explicit examples win",
			ctx:  ProjectContext{Examples: []string{"pay whoami"}},
			want: "pay whoami",
		},
		{
			name: "no drafts falls back to a plain find",
			ctx: ProjectContext{Collections: []CollectionInfo{
				{Slug: "crm-contacts", Features: []string{"trash"}},
			}},
			want: "pay find crm-contacts --limit 5 --select id",
		},
		{
			name: "no globals falls back to upload",
			ctx: ProjectContext{Collections: []CollectionInfo{
				{Slug: "media", Features: []string{"upload"}},
			}},
			want: "pay upload media ./file.png",
		},
		{
			name: "no globals and no upload falls back to count",
			ctx: ProjectContext{Collections: []CollectionInfo{
				{Slug: "redirects"},
			}},
			want: "pay count redirects",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := strings.Join(examples(tc.ctx), "\n")
			if !strings.Contains(got, tc.want) {
				t.Fatalf("examples = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestCollectionHasFeature(t *testing.T) {
	c := CollectionInfo{Features: []string{"drafts", "Versions"}}
	for _, f := range []string{"drafts", "versions", "VERSIONS"} {
		if !c.HasFeature(f) {
			t.Errorf("HasFeature(%q) = false", f)
		}
	}
	if c.HasFeature("upload") {
		t.Error("HasFeature(upload) = true")
	}
}
